### PR TITLE
decompressed roas.csv.xz and changed the urls

### PR DESCRIPTION
**Pull request by MAVRICK-1**
solved the issue of #117 

## Description

In this modification, requests.get() is used to fetch the .xz file content. Then, the content is decompressed using lzma.open() and read as a CSV file. The rest of the code remains the same as before for processing the CSV data.
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by MAVRICK-1** [comment]
@m-appel  and @romain-fontugne  can you review my PR :-)

**Comment by m-appel** [comment]
Hey, your PR looks good to me, please just fix the formatting (easiest is to setup `pre-commit` hooks as described [here](https://github.com/InternetHealthReport/internet-yellow-pages/blob/main/CONTRIBUTING.md)).

**Comment by MAVRICK-1** [comment]
@m-appel  I have modified the code struct, It passed all the tests.

**Review by m-appel — APPROVED** [review]
Thanks, looks good to me!

**Pull request merged**
