### PR TITLE
DNS remodeling

### PR DESCRIPTION
**Pull request by romain-fontugne**
Remodeling of DNS data

## Description

After multiple discussions we decided to improve the way we model DNS data. The main changes include de-coupling the DomainName and HostName nodes.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by romain-fontugne** [comment]
I have done most of the changes we discussed. Only things left are the cloudflare crawlers.

**Comment by romain-fontugne** [comment]
Forgot to lower umbrella in the config (readme should also be updated)

**Comment by romain-fontugne** [comment]
I have adjusted all crawlers for the new `DomainName` and `HostName` node definition. 

Still left: add `(:IP)-[:SERVE]-(:Service)` links.

**Comment by romain-fontugne** [comment]
I did a full run and got two errors:
- Couldn't get the MANRS data 
- flatdict exception in ripe.atlas_probes

These are completely unrelated to the modifications so I think we can now merge this PR. @m-appel are you planning any other changes here?

**Review by m-appel — APPROVED** [review]

**Comment by m-appel** [comment]
No, I think we can merge it (actually squash and merge, since it's many commits). I had the MANRS problem yesterday as well, but worked on rerun, I think they had some problems.

**Pull request merged**
